--- CURSOR
-- T-SQL
-- MANIPULAR LINHAS DE UMA TABELA INDIVIDUALMENTE
-- FASES: DECLARAÇÃO

DECLARE @NOME VARCHAR(200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS=0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

CLOSE CURSOR1
DEALLOCATE CURSOR1;


---------------
DECLARE @NOME1 VARCHAR(200)
DECLARE @ENDERECO VARCHAR(200)
DECLARE CURSOR2 CURSOR FOR 
SELECT NOME, ([ENDERECO 1]+' '+BAIRRO+' '+CIDADE+' '+ESTADO+' '+CEP) AS ENDCOMPLETO 
FROM [TABELA DE CLIENTES]
OPEN CURSOR2
FETCH NEXT FROM CURSOR2 INTO @NOME1, @ENDERECO
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME1+@ENDERECO
	FETCH NEXT FROM CURSOR2 INTO @NOME1, @ENDERECO
END
CLOSE CURSOR2
DEALLOCATE CURSOR2

--------------
-- ALEATORIOS
SELECT COUNT(*) FROM [TABELA DE CLIENTES];
SELECT dbo.NumeroAleatorio(1,16);

-- t-sql
DECLARE @CLIENTE_ALEATORIO VARCHAR(12)
DECLARE @VALOR_INICIAL INT
DECLARE @VALOR_FINAL INT
DECLARE @ALEATORIO INT
DECLARE @CONTADOR INT
SET @VALOR_INICIAL=1
SET @CONTADOR = 1
SELECT @VALOR_FINAL= COUNT(*) FROM [TABELA DE CLIENTES]
SET @ALEATORIO = dbo.NumeroAleatorio(@VALOR_INICIAL,@VALOR_FINAL)
DECLARE CURSOR3 CURSOR FOR SELECT CPF FROM [TABELA DE CLIENTES]
OPEN CURSOR3
FETCH NEXT FROM CURSOR3 INTO @CLIENTE_ALEATORIO
WHILE @CONTADOR<@ALEATORIO
BEGIN
	FETCH NEXT FROM CURSOR3 INTO @CLIENTE_ALEATORIO
	SET @CONTADOR=@CONTADOR + 1
END
CLOSE CURSOR3
DEALLOCATE CURSOR3
SELECT @CLIENTE_ALEATORIO, @ALEATORIO
