-- DECLARAÇÃO DE VARIAVEIS
--DECLARE @MATRICULA VARCHAR(5);
--DECLARE @NOME VARCHAR(100);
--DECLARE @PERCENTUAL FLOAT;
--DECLARE @DATA DATE;
--DECLARE @FERIAS BIT;
--DECLARE @BAIRRO VARCHAR(50);


--DECLARE @Cliente VARCHAR(10), @Idade INT, @DataNascimento DATE,@Custo FLOAT;
--SET @Cliente='João';
--SET @Idade=10;
--SET @DataNascimento='2007-10-01';
--SET @Custo=10.23;

DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT, @BAIRRO VARCHAR(50);
--SET @MATRICULA ='00240';
SET @NOME = 'Claudia Rodrigues';
SET @PERCENTUAL = 0.10;
--SET @DATA = '2012-03-12';
SET @FERIAS = 1;
SET @BAIRRO = 'Avenida';

PRINT @MATRICULA;
PRINT @NOME;
PRINT @PERCENTUAL;
PRINT @DATA;
PRINT @FERIAS;
PRINT @BAIRRO;

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
VALUES
(@MATRICULA,@NOME,@PERCENTUAL,@DATA,@FERIAS,@BAIRRO)

PRINT 'UM VENDEDOR INCLUÍDO'
------------------------------------
SET @MATRICULA='00244';
SET @NOME='Roberto Araujo';

PRINT @MATRICULA;
PRINT @NOME;
PRINT @PERCENTUAL;
PRINT @DATA;
PRINT @FERIAS;
PRINT @BAIRRO;

INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA,NOME,[PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
VALUES
(@MATRICULA,@NOME,@PERCENTUAL,@DATA,@FERIAS,@BAIRRO)

PRINT 'UM VENDEDOR INCLUÍDO'

SELECT * FROM [TABELA DE VENDEDORES];
-----------------------------
DECLARE @CPF VARCHAR(50), @NOME1 VARCHAR(100), @DATA_NASCIMENTO DATE,@IDADE INT;
SET @CPF='19290992743'

--SELECT * FROM [TABELA DE CLIENTES] WHERE CPF='19290992743';
SELECT @NOME1=NOME, @DATA_NASCIMENTO=[DATA DE NASCIMENTO],@IDADE=IDADE FROM [TABELA DE CLIENTES] WHERE CPF=@CPF;

PRINT @NOME1;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;
----------------------------
SELECT TOP 100 * FROM [NOTAS FISCAIS];
DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '2017-01-01'
PRINT @NUMNOTAS

------------------------------
SELECT NOME, CHARINDEX(' ',NOME), SUBSTRING(NOME,1,CHARINDEX(' ',NOME)-1) FROM [TABELA DE CLIENTES];

----------------------------
-- CONTROLE DE FLUXO
-- IF 

-- TESTAR SE UMA TABELA EXISTE
IF OBJECT_ID('TAB_TESTE','U') IS NOT NULL DROP TABLE TAB_TESTE;
IF OBJECT_ID('TAB_TESTE','U') IS NULL CREATE TABLE TAB_TESTE (ID VARCHAR(10));

DECLARE @IDADE_ALUNO INT;
DECLARE @FORMADO_INGLES BIT;
DECLARE @FORMADO_ALEMAO BIT;

SET @IDADE_ALUNO = 17;
SET @FORMADO_INGLES = 1;
SET @FORMADO_ALEMAO = 0;

IF ((@IDADE_ALUNO >= 18 OR @FORMADO_INGLES = 1) OR (@IDADE_ALUNO < 18 AND @FORMADO_ALEMAO = 1))
  PRINT 'EXPRESSAO VERDADEIRA';
ELSE
  PRINT 'EXPRESSAO FALSA';

---------------
-- TESTAR SE O DIA É UTIL
SELECT GETDATE();
SELECT DATENAME(WEEKDAY,GETDATE());
SELECT GETDATE(), DATEADD(DAY,5,GETDATE()), DATENAME(WEEKDAY,DATEADD(DAY,5,GETDATE()));

DECLARE @DIA_SEMANA VARCHAR(30);
DECLARE @NUMERO_DIAS INT;
SET @NUMERO_DIAS = 1;
SET @DIA_SEMANA = DATENAME(WEEKDAY,DATEADD(DAY,@NUMERO_DIAS,GETDATE()));
PRINT @DIA_SEMANA

IF @DIA_SEMANA='Domingo' OR @DIA_SEMANA='Sábado'
	PRINT 'Este dia é fim de semana';
ELSE 
	PRINT 'Este dia é durante semana';

------------
select * from [TABELA DE CLIENTES];
select BAIRRO, SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO] from [TABELA DE CLIENTES] group by BAIRRO;

DECLARE @LIMITE_MAXIMO FLOAT;
DECLARE @LIMITE_ATUAL FLOAT;
DECLARE @BAIRRO1 VARCHAR(20);

SET @LIMITE_MAXIMO = 500000;
SET @BAIRRO1 = 'Água Santa';
select @LIMITE_ATUAL=SUM([LIMITE DE CREDITO]) from [TABELA DE CLIENTES] WHERE BAIRRO=@BAIRRO1;
IF @LIMITE_MAXIMO<=@LIMITE_ATUAL
	PRINT 'Valor Estourou'
ELSE
	PRINT 'Valor não estourou'
-- OUTRA OPÇÃO: DECLARAR SOMENTE 2 VARIAVEIS
DECLARE @LIMITE_MAXIMO FLOAT;
DECLARE @BAIRRO1 VARCHAR(20);

SET @LIMITE_MAXIMO = 500000;
SET @BAIRRO1 = 'Água Santa';
IF @LIMITE_MAXIMO<=(select SUM([LIMITE DE CREDITO]) from [TABELA DE CLIENTES] WHERE BAIRRO=@BAIRRO1)
	PRINT 'Valor Estourou'
ELSE
	PRINT 'Valor não estourou'
